// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IGetChatHistoryRequest.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_IGetChatHistoryRequest_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_IGetChatHistoryRequest_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_IGetChatHistoryRequest_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_IGetChatHistoryRequest_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_IGetChatHistoryRequest_2eproto;
class IGetChatHistoryRequest;
class IGetChatHistoryRequestDefaultTypeInternal;
extern IGetChatHistoryRequestDefaultTypeInternal _IGetChatHistoryRequest_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::IGetChatHistoryRequest* Arena::CreateMaybeMessage<::IGetChatHistoryRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class IGetChatHistoryRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:IGetChatHistoryRequest) */ {
 public:
  inline IGetChatHistoryRequest() : IGetChatHistoryRequest(nullptr) {};
  virtual ~IGetChatHistoryRequest();

  IGetChatHistoryRequest(const IGetChatHistoryRequest& from);
  IGetChatHistoryRequest(IGetChatHistoryRequest&& from) noexcept
    : IGetChatHistoryRequest() {
    *this = ::std::move(from);
  }

  inline IGetChatHistoryRequest& operator=(const IGetChatHistoryRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline IGetChatHistoryRequest& operator=(IGetChatHistoryRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const IGetChatHistoryRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const IGetChatHistoryRequest* internal_default_instance() {
    return reinterpret_cast<const IGetChatHistoryRequest*>(
               &_IGetChatHistoryRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(IGetChatHistoryRequest& a, IGetChatHistoryRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(IGetChatHistoryRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IGetChatHistoryRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline IGetChatHistoryRequest* New() const final {
    return CreateMaybeMessage<IGetChatHistoryRequest>(nullptr);
  }

  IGetChatHistoryRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<IGetChatHistoryRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const IGetChatHistoryRequest& from);
  void MergeFrom(const IGetChatHistoryRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IGetChatHistoryRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "IGetChatHistoryRequest";
  }
  protected:
  explicit IGetChatHistoryRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_IGetChatHistoryRequest_2eproto);
    return ::descriptor_table_IGetChatHistoryRequest_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSenderIdFieldNumber = 1,
    kInterlocutorIdFieldNumber = 2,
  };
  // int32 sender_id = 1;
  void clear_sender_id();
  ::PROTOBUF_NAMESPACE_ID::int32 sender_id() const;
  void set_sender_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_sender_id() const;
  void _internal_set_sender_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 interlocutor_id = 2;
  void clear_interlocutor_id();
  ::PROTOBUF_NAMESPACE_ID::int32 interlocutor_id() const;
  void set_interlocutor_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_interlocutor_id() const;
  void _internal_set_interlocutor_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:IGetChatHistoryRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 sender_id_;
  ::PROTOBUF_NAMESPACE_ID::int32 interlocutor_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_IGetChatHistoryRequest_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// IGetChatHistoryRequest

// int32 sender_id = 1;
inline void IGetChatHistoryRequest::clear_sender_id() {
  sender_id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 IGetChatHistoryRequest::_internal_sender_id() const {
  return sender_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 IGetChatHistoryRequest::sender_id() const {
  // @@protoc_insertion_point(field_get:IGetChatHistoryRequest.sender_id)
  return _internal_sender_id();
}
inline void IGetChatHistoryRequest::_internal_set_sender_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  sender_id_ = value;
}
inline void IGetChatHistoryRequest::set_sender_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_sender_id(value);
  // @@protoc_insertion_point(field_set:IGetChatHistoryRequest.sender_id)
}

// int32 interlocutor_id = 2;
inline void IGetChatHistoryRequest::clear_interlocutor_id() {
  interlocutor_id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 IGetChatHistoryRequest::_internal_interlocutor_id() const {
  return interlocutor_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 IGetChatHistoryRequest::interlocutor_id() const {
  // @@protoc_insertion_point(field_get:IGetChatHistoryRequest.interlocutor_id)
  return _internal_interlocutor_id();
}
inline void IGetChatHistoryRequest::_internal_set_interlocutor_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  interlocutor_id_ = value;
}
inline void IGetChatHistoryRequest::set_interlocutor_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_interlocutor_id(value);
  // @@protoc_insertion_point(field_set:IGetChatHistoryRequest.interlocutor_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_IGetChatHistoryRequest_2eproto
